# Generated by Django 5.2.6 on 2025-09-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=200)),
                ('pages', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('academic_level', models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('GR', 'Graduate')], max_length=10)),
                ('formatting_style', models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA'), ('Chicago', 'Chicago')], max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
