# Generated by Django 5.2.4 on 2025-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True),
        ),
    ]
