# Generated by Django 5.2.4 on 2025-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_essayorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
    ]
